### ISSUE TITLE
Mismatch in content model of Operation between Reaction and Consumer

### ISSUE THREAD

**Issue by greenTara** [RuleML/reaction-ruleml#84]
In Reaction RuleML, the content model of Operation follows Rulebase. In the Relax NG of Deliberation, this is

RulebaseFormula.choice |=
  SimpleFormula-node.choice
  | And-fo-node.choice
  | Or-fo-node.choice
  | Negation-node.choice
  | NegationAsFailure-node.notallowed
  | Implication-node.choice
  | Forall-node.choice
  | Exists-fo-node.choice

This restriction in some sense preserves the Hornlog expressivity because a more general content model for Operation  would affect the expressivity when these Operations appear in the head of rules.

In Consumer RuleML, the content model for Operation is in some ways more permissive and in other ways more strict - it uses the content model for And, which is

AndFormula.choice |=
  SimpleFormula-node.choice
  | And-node.choice
  | Or-node.choice
  | Negation-node.choice
  | NegationAsFailure-node.choice
  | Implication-fo-node.choice
  | Forall-fo-node.choice
  | Exists-fo-node.choice

**Comment by apaschke** [comment]
updated the schema so that there is a distinction between operations for queries, rulebases, formulas, terms.
